// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: syncz/v1/syncz.proto

package synczv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SyncZap_SendMessage_FullMethodName        = "/syncz.v1.SyncZap/SendMessage"
	SyncZap_SendMedia_FullMethodName          = "/syncz.v1.SyncZap/SendMedia"
	SyncZap_StreamEvents_FullMethodName       = "/syncz.v1.SyncZap/StreamEvents"
	SyncZap_StartPairing_FullMethodName       = "/syncz.v1.SyncZap/StartPairing"
	SyncZap_CreateInstance_FullMethodName     = "/syncz.v1.SyncZap/CreateInstance"
	SyncZap_GetInstance_FullMethodName        = "/syncz.v1.SyncZap/GetInstance"
	SyncZap_ListInstances_FullMethodName      = "/syncz.v1.SyncZap/ListInstances"
	SyncZap_NewWizardLink_FullMethodName      = "/syncz.v1.SyncZap/NewWizardLink"
	SyncZap_RevokeInstance_FullMethodName     = "/syncz.v1.SyncZap/RevokeInstance"
	SyncZap_GetPolicy_FullMethodName          = "/syncz.v1.SyncZap/GetPolicy"
	SyncZap_UpdatePolicy_FullMethodName       = "/syncz.v1.SyncZap/UpdatePolicy"
	SyncZap_CreateGroup_FullMethodName        = "/syncz.v1.SyncZap/CreateGroup"
	SyncZap_UpdateGroupName_FullMethodName    = "/syncz.v1.SyncZap/UpdateGroupName"
	SyncZap_UpdateGroupPhoto_FullMethodName   = "/syncz.v1.SyncZap/UpdateGroupPhoto"
	SyncZap_AddParticipants_FullMethodName    = "/syncz.v1.SyncZap/AddParticipants"
	SyncZap_RemoveParticipants_FullMethodName = "/syncz.v1.SyncZap/RemoveParticipants"
	SyncZap_GroupInviteLink_FullMethodName    = "/syncz.v1.SyncZap/GroupInviteLink"
	SyncZap_LeaveGroup_FullMethodName         = "/syncz.v1.SyncZap/LeaveGroup"
	SyncZap_PinChat_FullMethodName            = "/syncz.v1.SyncZap/PinChat"
	SyncZap_MarkRead_FullMethodName           = "/syncz.v1.SyncZap/MarkRead"
	SyncZap_SetChatReadState_FullMethodName   = "/syncz.v1.SyncZap/SetChatReadState"
	SyncZap_CheckNumbers_FullMethodName       = "/syncz.v1.SyncZap/CheckNumbers"
	SyncZap_CreateGroupEvent_FullMethodName   = "/syncz.v1.SyncZap/CreateGroupEvent"
	SyncZap_UpdateGroupEvent_FullMethodName   = "/syncz.v1.SyncZap/UpdateGroupEvent"
	SyncZap_CancelGroupEvent_FullMethodName   = "/syncz.v1.SyncZap/CancelGroupEvent"
	SyncZap_ListGroupEvents_FullMethodName    = "/syncz.v1.SyncZap/ListGroupEvents"
	SyncZap_SendEventResponse_FullMethodName  = "/syncz.v1.SyncZap/SendEventResponse"
	SyncZap_CreatePoll_FullMethodName         = "/syncz.v1.SyncZap/CreatePoll"
	SyncZap_ListPolls_FullMethodName          = "/syncz.v1.SyncZap/ListPolls"
	SyncZap_GetPollResults_FullMethodName     = "/syncz.v1.SyncZap/GetPollResults"
	SyncZap_ClosePoll_FullMethodName          = "/syncz.v1.SyncZap/ClosePoll"
	SyncZap_PairingState_FullMethodName       = "/syncz.v1.SyncZap/PairingState"
	SyncZap_GetContract_FullMethodName        = "/syncz.v1.SyncZap/GetContract"
	SyncZap_GrantConsent_FullMethodName       = "/syncz.v1.SyncZap/GrantConsent"
	SyncZap_GetUsage_FullMethodName           = "/syncz.v1.SyncZap/GetUsage"
)

// SyncZapClient is the client API for SyncZap service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SyncZapClient interface {
	// ── Envio (unário) ──
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
	SendMedia(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SendMediaChunk, SendMessageResponse], error)
	// ── Eventos (servidor-stream) — o motivo principal do gRPC ──
	StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	// ── Pareamento headless (servidor-stream) ──
	StartPairing(ctx context.Context, in *StartPairingRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PairingEvent], error)
	// ── Gestão ──
	CreateInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (*Instance, error)
	GetInstance(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*Instance, error)
	ListInstances(ctx context.Context, in *ListInstancesRequest, opts ...grpc.CallOption) (*ListInstancesResponse, error)
	NewWizardLink(ctx context.Context, in *NewWizardLinkRequest, opts ...grpc.CallOption) (*WizardLink, error)
	RevokeInstance(ctx context.Context, in *RevokeInstanceRequest, opts ...grpc.CallOption) (*Instance, error)
	// ── Política ──
	GetPolicy(ctx context.Context, in *GetPolicyRequest, opts ...grpc.CallOption) (*Policy, error)
	UpdatePolicy(ctx context.Context, in *UpdatePolicyRequest, opts ...grpc.CallOption) (*Policy, error)
	// ── Grupos e Operações Auxiliares (cada um exige o escopo correspondente — ver §6) ──
	CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*Group, error)
	UpdateGroupName(ctx context.Context, in *UpdateGroupNameRequest, opts ...grpc.CallOption) (*Group, error)
	UpdateGroupPhoto(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[GroupPhotoChunk, Group], error)
	AddParticipants(ctx context.Context, in *AddParticipantsRequest, opts ...grpc.CallOption) (*AddParticipantsResponse, error)
	RemoveParticipants(ctx context.Context, in *RemoveParticipantsRequest, opts ...grpc.CallOption) (*RemoveParticipantsResponse, error)
	GroupInviteLink(ctx context.Context, in *GroupInviteLinkRequest, opts ...grpc.CallOption) (*GroupInviteLinkResponse, error)
	LeaveGroup(ctx context.Context, in *LeaveGroupRequest, opts ...grpc.CallOption) (*LeaveGroupResponse, error)
	PinChat(ctx context.Context, in *PinChatRequest, opts ...grpc.CallOption) (*PinChatResponse, error)
	MarkRead(ctx context.Context, in *MarkReadRequest, opts ...grpc.CallOption) (*MarkReadResponse, error)
	// SetChatReadState marca a conversa como lida ou nao lida via mutacao de
	// app state (distinto de MarkRead, que so' manda recibo de mensagens
	// especificas) -- funciona igual para DM com contato, self-chat e grupo
	// (task 383).
	SetChatReadState(ctx context.Context, in *SetChatReadStateRequest, opts ...grpc.CallOption) (*SetChatReadStateResponse, error)
	CheckNumbers(ctx context.Context, in *CheckNumbersRequest, opts ...grpc.CallOption) (*CheckNumbersResponse, error)
	// ── Eventos de grupo (cada um exige escopo proprio) ──
	// O evento e' o unico mecanismo que produz notificacao LOCAL no aparelho do
	// titular no horario marcado -- mensagem da propria conta nao gera push.
	// Ver docs/specs/sprint-12-2-eventos-e-enquetes.md.
	CreateGroupEvent(ctx context.Context, in *CreateGroupEventRequest, opts ...grpc.CallOption) (*GroupEvent, error)
	UpdateGroupEvent(ctx context.Context, in *UpdateGroupEventRequest, opts ...grpc.CallOption) (*GroupEvent, error)
	CancelGroupEvent(ctx context.Context, in *CancelGroupEventRequest, opts ...grpc.CallOption) (*GroupEvent, error)
	ListGroupEvents(ctx context.Context, in *ListGroupEventsRequest, opts ...grpc.CallOption) (*ListGroupEventsResponse, error)
	SendEventResponse(ctx context.Context, in *SendEventResponseRequest, opts ...grpc.CallOption) (*SendEventResponseResponse, error)
	// ── Enquetes de grupo ──
	// Enquete com selectable_count > 1 e' um CHECKLIST; nao existe tipo proprio.
	CreatePoll(ctx context.Context, in *CreatePollRequest, opts ...grpc.CallOption) (*Poll, error)
	ListPolls(ctx context.Context, in *ListPollsRequest, opts ...grpc.CallOption) (*ListPollsResponse, error)
	GetPollResults(ctx context.Context, in *GetPollResultsRequest, opts ...grpc.CallOption) (*PollResults, error)
	ClosePoll(ctx context.Context, in *ClosePollRequest, opts ...grpc.CallOption) (*Poll, error)
	// ── Onboarding transparente ──
	// O tenant desenha a propria jornada: obtem o QR como string, o termo e os
	// escopos para compor UMA tela de autorizacao, e registra o aceite do
	// titular sem passar pelo HTML do wizard hospedado.
	PairingState(ctx context.Context, in *PairingStateRequest, opts ...grpc.CallOption) (*PairingStateInfo, error)
	GetContract(ctx context.Context, in *GetContractRequest, opts ...grpc.CallOption) (*ContractInfo, error)
	GrantConsent(ctx context.Context, in *GrantConsentRequest, opts ...grpc.CallOption) (*GrantConsentResponse, error)
	GetUsage(ctx context.Context, in *GetUsageRequest, opts ...grpc.CallOption) (*GetUsageResponse, error)
}

type syncZapClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncZapClient(cc grpc.ClientConnInterface) SyncZapClient {
	return &syncZapClient{cc}
}

func (c *syncZapClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, SyncZap_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncZapClient) SendMedia(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SendMediaChunk, SendMessageResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SyncZap_ServiceDesc.Streams[0], SyncZap_SendMedia_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SendMediaChunk, SendMessageResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SyncZap_SendMediaClient = grpc.ClientStreamingClient[SendMediaChunk, SendMessageResponse]

func (c *syncZapClient) StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SyncZap_ServiceDesc.Streams[1], SyncZap_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamEventsRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SyncZap_StreamEventsClient = grpc.ServerStreamingClient[Event]

func (c *syncZapClient) StartPairing(ctx context.Context, in *StartPairingRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PairingEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SyncZap_ServiceDesc.Streams[2], SyncZap_StartPairing_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StartPairingRequest, PairingEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SyncZap_StartPairingClient = grpc.ServerStreamingClient[PairingEvent]

func (c *syncZapClient) CreateInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (*Instance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Instance)
	err := c.cc.Invoke(ctx, SyncZap_CreateInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncZapClient) GetInstance(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*Instance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Instance)
	err := c.cc.Invoke(ctx, SyncZap_GetInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncZapClient) ListInstances(ctx context.Context, in *ListInstancesRequest, opts ...grpc.CallOption) (*ListInstancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInstancesResponse)
	err := c.cc.Invoke(ctx, SyncZap_ListInstances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncZapClient) NewWizardLink(ctx context.Context, in *NewWizardLinkRequest, opts ...grpc.CallOption) (*WizardLink, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WizardLink)
	err := c.cc.Invoke(ctx, SyncZap_NewWizardLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncZapClient) RevokeInstance(ctx context.Context, in *RevokeInstanceRequest, opts ...grpc.CallOption) (*Instance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Instance)
	err := c.cc.Invoke(ctx, SyncZap_RevokeInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncZapClient) GetPolicy(ctx context.Context, in *GetPolicyRequest, opts ...grpc.CallOption) (*Policy, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Policy)
	err := c.cc.Invoke(ctx, SyncZap_GetPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncZapClient) UpdatePolicy(ctx context.Context, in *UpdatePolicyRequest, opts ...grpc.CallOption) (*Policy, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Policy)
	err := c.cc.Invoke(ctx, SyncZap_UpdatePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncZapClient) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*Group, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Group)
	err := c.cc.Invoke(ctx, SyncZap_CreateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncZapClient) UpdateGroupName(ctx context.Context, in *UpdateGroupNameRequest, opts ...grpc.CallOption) (*Group, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Group)
	err := c.cc.Invoke(ctx, SyncZap_UpdateGroupName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncZapClient) UpdateGroupPhoto(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[GroupPhotoChunk, Group], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SyncZap_ServiceDesc.Streams[3], SyncZap_UpdateGroupPhoto_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GroupPhotoChunk, Group]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SyncZap_UpdateGroupPhotoClient = grpc.ClientStreamingClient[GroupPhotoChunk, Group]

func (c *syncZapClient) AddParticipants(ctx context.Context, in *AddParticipantsRequest, opts ...grpc.CallOption) (*AddParticipantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddParticipantsResponse)
	err := c.cc.Invoke(ctx, SyncZap_AddParticipants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncZapClient) RemoveParticipants(ctx context.Context, in *RemoveParticipantsRequest, opts ...grpc.CallOption) (*RemoveParticipantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveParticipantsResponse)
	err := c.cc.Invoke(ctx, SyncZap_RemoveParticipants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncZapClient) GroupInviteLink(ctx context.Context, in *GroupInviteLinkRequest, opts ...grpc.CallOption) (*GroupInviteLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupInviteLinkResponse)
	err := c.cc.Invoke(ctx, SyncZap_GroupInviteLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncZapClient) LeaveGroup(ctx context.Context, in *LeaveGroupRequest, opts ...grpc.CallOption) (*LeaveGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaveGroupResponse)
	err := c.cc.Invoke(ctx, SyncZap_LeaveGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncZapClient) PinChat(ctx context.Context, in *PinChatRequest, opts ...grpc.CallOption) (*PinChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PinChatResponse)
	err := c.cc.Invoke(ctx, SyncZap_PinChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncZapClient) MarkRead(ctx context.Context, in *MarkReadRequest, opts ...grpc.CallOption) (*MarkReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkReadResponse)
	err := c.cc.Invoke(ctx, SyncZap_MarkRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncZapClient) SetChatReadState(ctx context.Context, in *SetChatReadStateRequest, opts ...grpc.CallOption) (*SetChatReadStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetChatReadStateResponse)
	err := c.cc.Invoke(ctx, SyncZap_SetChatReadState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncZapClient) CheckNumbers(ctx context.Context, in *CheckNumbersRequest, opts ...grpc.CallOption) (*CheckNumbersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckNumbersResponse)
	err := c.cc.Invoke(ctx, SyncZap_CheckNumbers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncZapClient) CreateGroupEvent(ctx context.Context, in *CreateGroupEventRequest, opts ...grpc.CallOption) (*GroupEvent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupEvent)
	err := c.cc.Invoke(ctx, SyncZap_CreateGroupEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncZapClient) UpdateGroupEvent(ctx context.Context, in *UpdateGroupEventRequest, opts ...grpc.CallOption) (*GroupEvent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupEvent)
	err := c.cc.Invoke(ctx, SyncZap_UpdateGroupEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncZapClient) CancelGroupEvent(ctx context.Context, in *CancelGroupEventRequest, opts ...grpc.CallOption) (*GroupEvent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupEvent)
	err := c.cc.Invoke(ctx, SyncZap_CancelGroupEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncZapClient) ListGroupEvents(ctx context.Context, in *ListGroupEventsRequest, opts ...grpc.CallOption) (*ListGroupEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGroupEventsResponse)
	err := c.cc.Invoke(ctx, SyncZap_ListGroupEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncZapClient) SendEventResponse(ctx context.Context, in *SendEventResponseRequest, opts ...grpc.CallOption) (*SendEventResponseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendEventResponseResponse)
	err := c.cc.Invoke(ctx, SyncZap_SendEventResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncZapClient) CreatePoll(ctx context.Context, in *CreatePollRequest, opts ...grpc.CallOption) (*Poll, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Poll)
	err := c.cc.Invoke(ctx, SyncZap_CreatePoll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncZapClient) ListPolls(ctx context.Context, in *ListPollsRequest, opts ...grpc.CallOption) (*ListPollsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPollsResponse)
	err := c.cc.Invoke(ctx, SyncZap_ListPolls_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncZapClient) GetPollResults(ctx context.Context, in *GetPollResultsRequest, opts ...grpc.CallOption) (*PollResults, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PollResults)
	err := c.cc.Invoke(ctx, SyncZap_GetPollResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncZapClient) ClosePoll(ctx context.Context, in *ClosePollRequest, opts ...grpc.CallOption) (*Poll, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Poll)
	err := c.cc.Invoke(ctx, SyncZap_ClosePoll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncZapClient) PairingState(ctx context.Context, in *PairingStateRequest, opts ...grpc.CallOption) (*PairingStateInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PairingStateInfo)
	err := c.cc.Invoke(ctx, SyncZap_PairingState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncZapClient) GetContract(ctx context.Context, in *GetContractRequest, opts ...grpc.CallOption) (*ContractInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContractInfo)
	err := c.cc.Invoke(ctx, SyncZap_GetContract_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncZapClient) GrantConsent(ctx context.Context, in *GrantConsentRequest, opts ...grpc.CallOption) (*GrantConsentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrantConsentResponse)
	err := c.cc.Invoke(ctx, SyncZap_GrantConsent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncZapClient) GetUsage(ctx context.Context, in *GetUsageRequest, opts ...grpc.CallOption) (*GetUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUsageResponse)
	err := c.cc.Invoke(ctx, SyncZap_GetUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyncZapServer is the server API for SyncZap service.
// All implementations must embed UnimplementedSyncZapServer
// for forward compatibility.
type SyncZapServer interface {
	// ── Envio (unário) ──
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	SendMedia(grpc.ClientStreamingServer[SendMediaChunk, SendMessageResponse]) error
	// ── Eventos (servidor-stream) — o motivo principal do gRPC ──
	StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[Event]) error
	// ── Pareamento headless (servidor-stream) ──
	StartPairing(*StartPairingRequest, grpc.ServerStreamingServer[PairingEvent]) error
	// ── Gestão ──
	CreateInstance(context.Context, *CreateInstanceRequest) (*Instance, error)
	GetInstance(context.Context, *GetInstanceRequest) (*Instance, error)
	ListInstances(context.Context, *ListInstancesRequest) (*ListInstancesResponse, error)
	NewWizardLink(context.Context, *NewWizardLinkRequest) (*WizardLink, error)
	RevokeInstance(context.Context, *RevokeInstanceRequest) (*Instance, error)
	// ── Política ──
	GetPolicy(context.Context, *GetPolicyRequest) (*Policy, error)
	UpdatePolicy(context.Context, *UpdatePolicyRequest) (*Policy, error)
	// ── Grupos e Operações Auxiliares (cada um exige o escopo correspondente — ver §6) ──
	CreateGroup(context.Context, *CreateGroupRequest) (*Group, error)
	UpdateGroupName(context.Context, *UpdateGroupNameRequest) (*Group, error)
	UpdateGroupPhoto(grpc.ClientStreamingServer[GroupPhotoChunk, Group]) error
	AddParticipants(context.Context, *AddParticipantsRequest) (*AddParticipantsResponse, error)
	RemoveParticipants(context.Context, *RemoveParticipantsRequest) (*RemoveParticipantsResponse, error)
	GroupInviteLink(context.Context, *GroupInviteLinkRequest) (*GroupInviteLinkResponse, error)
	LeaveGroup(context.Context, *LeaveGroupRequest) (*LeaveGroupResponse, error)
	PinChat(context.Context, *PinChatRequest) (*PinChatResponse, error)
	MarkRead(context.Context, *MarkReadRequest) (*MarkReadResponse, error)
	// SetChatReadState marca a conversa como lida ou nao lida via mutacao de
	// app state (distinto de MarkRead, que so' manda recibo de mensagens
	// especificas) -- funciona igual para DM com contato, self-chat e grupo
	// (task 383).
	SetChatReadState(context.Context, *SetChatReadStateRequest) (*SetChatReadStateResponse, error)
	CheckNumbers(context.Context, *CheckNumbersRequest) (*CheckNumbersResponse, error)
	// ── Eventos de grupo (cada um exige escopo proprio) ──
	// O evento e' o unico mecanismo que produz notificacao LOCAL no aparelho do
	// titular no horario marcado -- mensagem da propria conta nao gera push.
	// Ver docs/specs/sprint-12-2-eventos-e-enquetes.md.
	CreateGroupEvent(context.Context, *CreateGroupEventRequest) (*GroupEvent, error)
	UpdateGroupEvent(context.Context, *UpdateGroupEventRequest) (*GroupEvent, error)
	CancelGroupEvent(context.Context, *CancelGroupEventRequest) (*GroupEvent, error)
	ListGroupEvents(context.Context, *ListGroupEventsRequest) (*ListGroupEventsResponse, error)
	SendEventResponse(context.Context, *SendEventResponseRequest) (*SendEventResponseResponse, error)
	// ── Enquetes de grupo ──
	// Enquete com selectable_count > 1 e' um CHECKLIST; nao existe tipo proprio.
	CreatePoll(context.Context, *CreatePollRequest) (*Poll, error)
	ListPolls(context.Context, *ListPollsRequest) (*ListPollsResponse, error)
	GetPollResults(context.Context, *GetPollResultsRequest) (*PollResults, error)
	ClosePoll(context.Context, *ClosePollRequest) (*Poll, error)
	// ── Onboarding transparente ──
	// O tenant desenha a propria jornada: obtem o QR como string, o termo e os
	// escopos para compor UMA tela de autorizacao, e registra o aceite do
	// titular sem passar pelo HTML do wizard hospedado.
	PairingState(context.Context, *PairingStateRequest) (*PairingStateInfo, error)
	GetContract(context.Context, *GetContractRequest) (*ContractInfo, error)
	GrantConsent(context.Context, *GrantConsentRequest) (*GrantConsentResponse, error)
	GetUsage(context.Context, *GetUsageRequest) (*GetUsageResponse, error)
	mustEmbedUnimplementedSyncZapServer()
}

// UnimplementedSyncZapServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSyncZapServer struct{}

func (UnimplementedSyncZapServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedSyncZapServer) SendMedia(grpc.ClientStreamingServer[SendMediaChunk, SendMessageResponse]) error {
	return status.Error(codes.Unimplemented, "method SendMedia not implemented")
}
func (UnimplementedSyncZapServer) StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedSyncZapServer) StartPairing(*StartPairingRequest, grpc.ServerStreamingServer[PairingEvent]) error {
	return status.Error(codes.Unimplemented, "method StartPairing not implemented")
}
func (UnimplementedSyncZapServer) CreateInstance(context.Context, *CreateInstanceRequest) (*Instance, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateInstance not implemented")
}
func (UnimplementedSyncZapServer) GetInstance(context.Context, *GetInstanceRequest) (*Instance, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInstance not implemented")
}
func (UnimplementedSyncZapServer) ListInstances(context.Context, *ListInstancesRequest) (*ListInstancesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInstances not implemented")
}
func (UnimplementedSyncZapServer) NewWizardLink(context.Context, *NewWizardLinkRequest) (*WizardLink, error) {
	return nil, status.Error(codes.Unimplemented, "method NewWizardLink not implemented")
}
func (UnimplementedSyncZapServer) RevokeInstance(context.Context, *RevokeInstanceRequest) (*Instance, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeInstance not implemented")
}
func (UnimplementedSyncZapServer) GetPolicy(context.Context, *GetPolicyRequest) (*Policy, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPolicy not implemented")
}
func (UnimplementedSyncZapServer) UpdatePolicy(context.Context, *UpdatePolicyRequest) (*Policy, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePolicy not implemented")
}
func (UnimplementedSyncZapServer) CreateGroup(context.Context, *CreateGroupRequest) (*Group, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGroup not implemented")
}
func (UnimplementedSyncZapServer) UpdateGroupName(context.Context, *UpdateGroupNameRequest) (*Group, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGroupName not implemented")
}
func (UnimplementedSyncZapServer) UpdateGroupPhoto(grpc.ClientStreamingServer[GroupPhotoChunk, Group]) error {
	return status.Error(codes.Unimplemented, "method UpdateGroupPhoto not implemented")
}
func (UnimplementedSyncZapServer) AddParticipants(context.Context, *AddParticipantsRequest) (*AddParticipantsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddParticipants not implemented")
}
func (UnimplementedSyncZapServer) RemoveParticipants(context.Context, *RemoveParticipantsRequest) (*RemoveParticipantsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveParticipants not implemented")
}
func (UnimplementedSyncZapServer) GroupInviteLink(context.Context, *GroupInviteLinkRequest) (*GroupInviteLinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GroupInviteLink not implemented")
}
func (UnimplementedSyncZapServer) LeaveGroup(context.Context, *LeaveGroupRequest) (*LeaveGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LeaveGroup not implemented")
}
func (UnimplementedSyncZapServer) PinChat(context.Context, *PinChatRequest) (*PinChatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PinChat not implemented")
}
func (UnimplementedSyncZapServer) MarkRead(context.Context, *MarkReadRequest) (*MarkReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkRead not implemented")
}
func (UnimplementedSyncZapServer) SetChatReadState(context.Context, *SetChatReadStateRequest) (*SetChatReadStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetChatReadState not implemented")
}
func (UnimplementedSyncZapServer) CheckNumbers(context.Context, *CheckNumbersRequest) (*CheckNumbersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckNumbers not implemented")
}
func (UnimplementedSyncZapServer) CreateGroupEvent(context.Context, *CreateGroupEventRequest) (*GroupEvent, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGroupEvent not implemented")
}
func (UnimplementedSyncZapServer) UpdateGroupEvent(context.Context, *UpdateGroupEventRequest) (*GroupEvent, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGroupEvent not implemented")
}
func (UnimplementedSyncZapServer) CancelGroupEvent(context.Context, *CancelGroupEventRequest) (*GroupEvent, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelGroupEvent not implemented")
}
func (UnimplementedSyncZapServer) ListGroupEvents(context.Context, *ListGroupEventsRequest) (*ListGroupEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGroupEvents not implemented")
}
func (UnimplementedSyncZapServer) SendEventResponse(context.Context, *SendEventResponseRequest) (*SendEventResponseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendEventResponse not implemented")
}
func (UnimplementedSyncZapServer) CreatePoll(context.Context, *CreatePollRequest) (*Poll, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePoll not implemented")
}
func (UnimplementedSyncZapServer) ListPolls(context.Context, *ListPollsRequest) (*ListPollsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPolls not implemented")
}
func (UnimplementedSyncZapServer) GetPollResults(context.Context, *GetPollResultsRequest) (*PollResults, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPollResults not implemented")
}
func (UnimplementedSyncZapServer) ClosePoll(context.Context, *ClosePollRequest) (*Poll, error) {
	return nil, status.Error(codes.Unimplemented, "method ClosePoll not implemented")
}
func (UnimplementedSyncZapServer) PairingState(context.Context, *PairingStateRequest) (*PairingStateInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method PairingState not implemented")
}
func (UnimplementedSyncZapServer) GetContract(context.Context, *GetContractRequest) (*ContractInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContract not implemented")
}
func (UnimplementedSyncZapServer) GrantConsent(context.Context, *GrantConsentRequest) (*GrantConsentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GrantConsent not implemented")
}
func (UnimplementedSyncZapServer) GetUsage(context.Context, *GetUsageRequest) (*GetUsageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUsage not implemented")
}
func (UnimplementedSyncZapServer) mustEmbedUnimplementedSyncZapServer() {}
func (UnimplementedSyncZapServer) testEmbeddedByValue()                 {}

// UnsafeSyncZapServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyncZapServer will
// result in compilation errors.
type UnsafeSyncZapServer interface {
	mustEmbedUnimplementedSyncZapServer()
}

func RegisterSyncZapServer(s grpc.ServiceRegistrar, srv SyncZapServer) {
	// If the following call panics, it indicates UnimplementedSyncZapServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SyncZap_ServiceDesc, srv)
}

func _SyncZap_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncZapServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncZap_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncZapServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncZap_SendMedia_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SyncZapServer).SendMedia(&grpc.GenericServerStream[SendMediaChunk, SendMessageResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SyncZap_SendMediaServer = grpc.ClientStreamingServer[SendMediaChunk, SendMessageResponse]

func _SyncZap_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SyncZapServer).StreamEvents(m, &grpc.GenericServerStream[StreamEventsRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SyncZap_StreamEventsServer = grpc.ServerStreamingServer[Event]

func _SyncZap_StartPairing_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StartPairingRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SyncZapServer).StartPairing(m, &grpc.GenericServerStream[StartPairingRequest, PairingEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SyncZap_StartPairingServer = grpc.ServerStreamingServer[PairingEvent]

func _SyncZap_CreateInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncZapServer).CreateInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncZap_CreateInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncZapServer).CreateInstance(ctx, req.(*CreateInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncZap_GetInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncZapServer).GetInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncZap_GetInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncZapServer).GetInstance(ctx, req.(*GetInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncZap_ListInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInstancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncZapServer).ListInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncZap_ListInstances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncZapServer).ListInstances(ctx, req.(*ListInstancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncZap_NewWizardLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewWizardLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncZapServer).NewWizardLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncZap_NewWizardLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncZapServer).NewWizardLink(ctx, req.(*NewWizardLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncZap_RevokeInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncZapServer).RevokeInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncZap_RevokeInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncZapServer).RevokeInstance(ctx, req.(*RevokeInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncZap_GetPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncZapServer).GetPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncZap_GetPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncZapServer).GetPolicy(ctx, req.(*GetPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncZap_UpdatePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncZapServer).UpdatePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncZap_UpdatePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncZapServer).UpdatePolicy(ctx, req.(*UpdatePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncZap_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncZapServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncZap_CreateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncZapServer).CreateGroup(ctx, req.(*CreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncZap_UpdateGroupName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGroupNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncZapServer).UpdateGroupName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncZap_UpdateGroupName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncZapServer).UpdateGroupName(ctx, req.(*UpdateGroupNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncZap_UpdateGroupPhoto_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SyncZapServer).UpdateGroupPhoto(&grpc.GenericServerStream[GroupPhotoChunk, Group]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SyncZap_UpdateGroupPhotoServer = grpc.ClientStreamingServer[GroupPhotoChunk, Group]

func _SyncZap_AddParticipants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddParticipantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncZapServer).AddParticipants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncZap_AddParticipants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncZapServer).AddParticipants(ctx, req.(*AddParticipantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncZap_RemoveParticipants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveParticipantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncZapServer).RemoveParticipants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncZap_RemoveParticipants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncZapServer).RemoveParticipants(ctx, req.(*RemoveParticipantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncZap_GroupInviteLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupInviteLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncZapServer).GroupInviteLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncZap_GroupInviteLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncZapServer).GroupInviteLink(ctx, req.(*GroupInviteLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncZap_LeaveGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncZapServer).LeaveGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncZap_LeaveGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncZapServer).LeaveGroup(ctx, req.(*LeaveGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncZap_PinChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PinChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncZapServer).PinChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncZap_PinChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncZapServer).PinChat(ctx, req.(*PinChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncZap_MarkRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncZapServer).MarkRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncZap_MarkRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncZapServer).MarkRead(ctx, req.(*MarkReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncZap_SetChatReadState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetChatReadStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncZapServer).SetChatReadState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncZap_SetChatReadState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncZapServer).SetChatReadState(ctx, req.(*SetChatReadStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncZap_CheckNumbers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckNumbersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncZapServer).CheckNumbers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncZap_CheckNumbers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncZapServer).CheckNumbers(ctx, req.(*CheckNumbersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncZap_CreateGroupEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncZapServer).CreateGroupEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncZap_CreateGroupEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncZapServer).CreateGroupEvent(ctx, req.(*CreateGroupEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncZap_UpdateGroupEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGroupEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncZapServer).UpdateGroupEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncZap_UpdateGroupEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncZapServer).UpdateGroupEvent(ctx, req.(*UpdateGroupEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncZap_CancelGroupEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelGroupEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncZapServer).CancelGroupEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncZap_CancelGroupEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncZapServer).CancelGroupEvent(ctx, req.(*CancelGroupEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncZap_ListGroupEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncZapServer).ListGroupEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncZap_ListGroupEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncZapServer).ListGroupEvents(ctx, req.(*ListGroupEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncZap_SendEventResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEventResponseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncZapServer).SendEventResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncZap_SendEventResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncZapServer).SendEventResponse(ctx, req.(*SendEventResponseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncZap_CreatePoll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncZapServer).CreatePoll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncZap_CreatePoll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncZapServer).CreatePoll(ctx, req.(*CreatePollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncZap_ListPolls_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPollsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncZapServer).ListPolls(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncZap_ListPolls_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncZapServer).ListPolls(ctx, req.(*ListPollsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncZap_GetPollResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPollResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncZapServer).GetPollResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncZap_GetPollResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncZapServer).GetPollResults(ctx, req.(*GetPollResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncZap_ClosePoll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClosePollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncZapServer).ClosePoll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncZap_ClosePoll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncZapServer).ClosePoll(ctx, req.(*ClosePollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncZap_PairingState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PairingStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncZapServer).PairingState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncZap_PairingState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncZapServer).PairingState(ctx, req.(*PairingStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncZap_GetContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncZapServer).GetContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncZap_GetContract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncZapServer).GetContract(ctx, req.(*GetContractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncZap_GrantConsent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantConsentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncZapServer).GrantConsent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncZap_GrantConsent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncZapServer).GrantConsent(ctx, req.(*GrantConsentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncZap_GetUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncZapServer).GetUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncZap_GetUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncZapServer).GetUsage(ctx, req.(*GetUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SyncZap_ServiceDesc is the grpc.ServiceDesc for SyncZap service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SyncZap_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "syncz.v1.SyncZap",
	HandlerType: (*SyncZapServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _SyncZap_SendMessage_Handler,
		},
		{
			MethodName: "CreateInstance",
			Handler:    _SyncZap_CreateInstance_Handler,
		},
		{
			MethodName: "GetInstance",
			Handler:    _SyncZap_GetInstance_Handler,
		},
		{
			MethodName: "ListInstances",
			Handler:    _SyncZap_ListInstances_Handler,
		},
		{
			MethodName: "NewWizardLink",
			Handler:    _SyncZap_NewWizardLink_Handler,
		},
		{
			MethodName: "RevokeInstance",
			Handler:    _SyncZap_RevokeInstance_Handler,
		},
		{
			MethodName: "GetPolicy",
			Handler:    _SyncZap_GetPolicy_Handler,
		},
		{
			MethodName: "UpdatePolicy",
			Handler:    _SyncZap_UpdatePolicy_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _SyncZap_CreateGroup_Handler,
		},
		{
			MethodName: "UpdateGroupName",
			Handler:    _SyncZap_UpdateGroupName_Handler,
		},
		{
			MethodName: "AddParticipants",
			Handler:    _SyncZap_AddParticipants_Handler,
		},
		{
			MethodName: "RemoveParticipants",
			Handler:    _SyncZap_RemoveParticipants_Handler,
		},
		{
			MethodName: "GroupInviteLink",
			Handler:    _SyncZap_GroupInviteLink_Handler,
		},
		{
			MethodName: "LeaveGroup",
			Handler:    _SyncZap_LeaveGroup_Handler,
		},
		{
			MethodName: "PinChat",
			Handler:    _SyncZap_PinChat_Handler,
		},
		{
			MethodName: "MarkRead",
			Handler:    _SyncZap_MarkRead_Handler,
		},
		{
			MethodName: "SetChatReadState",
			Handler:    _SyncZap_SetChatReadState_Handler,
		},
		{
			MethodName: "CheckNumbers",
			Handler:    _SyncZap_CheckNumbers_Handler,
		},
		{
			MethodName: "CreateGroupEvent",
			Handler:    _SyncZap_CreateGroupEvent_Handler,
		},
		{
			MethodName: "UpdateGroupEvent",
			Handler:    _SyncZap_UpdateGroupEvent_Handler,
		},
		{
			MethodName: "CancelGroupEvent",
			Handler:    _SyncZap_CancelGroupEvent_Handler,
		},
		{
			MethodName: "ListGroupEvents",
			Handler:    _SyncZap_ListGroupEvents_Handler,
		},
		{
			MethodName: "SendEventResponse",
			Handler:    _SyncZap_SendEventResponse_Handler,
		},
		{
			MethodName: "CreatePoll",
			Handler:    _SyncZap_CreatePoll_Handler,
		},
		{
			MethodName: "ListPolls",
			Handler:    _SyncZap_ListPolls_Handler,
		},
		{
			MethodName: "GetPollResults",
			Handler:    _SyncZap_GetPollResults_Handler,
		},
		{
			MethodName: "ClosePoll",
			Handler:    _SyncZap_ClosePoll_Handler,
		},
		{
			MethodName: "PairingState",
			Handler:    _SyncZap_PairingState_Handler,
		},
		{
			MethodName: "GetContract",
			Handler:    _SyncZap_GetContract_Handler,
		},
		{
			MethodName: "GrantConsent",
			Handler:    _SyncZap_GrantConsent_Handler,
		},
		{
			MethodName: "GetUsage",
			Handler:    _SyncZap_GetUsage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendMedia",
			Handler:       _SyncZap_SendMedia_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamEvents",
			Handler:       _SyncZap_StreamEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StartPairing",
			Handler:       _SyncZap_StartPairing_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UpdateGroupPhoto",
			Handler:       _SyncZap_UpdateGroupPhoto_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "syncz/v1/syncz.proto",
}
